### ISSUE TITLE
记账页面优化

### ISSUE THREAD

**Issue by 1483523635** [1483523635/money-tracker#5]
记账页面 确定按钮点击之后 不要back到上一个界面 跳转到账单详情页面

**Comment by 1483523635** [comment]
跳转到day页面

**Comment by qianfeiqianlan** [comment]
这么勤快，这时候还在写代码

XiaoQu <notifications@github.com> 于2020年6月12日周五 下午5:12写道：

**Comment by 1483523635** [comment]
beach 了一个多月了🤡
